# see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages
name: Github Publish Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      BRANCH: ${{github.ref}}
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com/
          scope: '@seolhun'

      - name: Install
        run: npm ci

      - name: Bootstrap
        run: npm run bs

      - name: Linting
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build --if-present

      - name: Publish package
        run: npm run release

      - name: "Build Changelog"
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: "configuration.json"

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: dev-travis
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
